// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eStore.Infrastructure.Data;

#nullable disable

namespace eStore.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("eStore.Domain.Entity.Batch", b =>
                {
                    b.Property<int>("BatchNumber")
                        .HasColumnType("int");

                    b.Property<string>("BatchDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Product_Id")
                        .HasColumnType("int");

                    b.HasKey("BatchNumber");

                    b.HasIndex("Product_Id");

                    b.ToTable("Batches");

                    b.HasData(
                        new
                        {
                            BatchNumber = 10200,
                            BatchDetails = "Some details goes here",
                            Product_Id = 1
                        });
                });

            modelBuilder.Entity("eStore.Domain.Entity.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("eStore.Domain.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateOnly>("PublishDate")
                        .HasColumnType("date");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("UpdateDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Brand = "Samsung",
                            Category = "Smartphones",
                            ImageURL = "https://rukminim2.flixcart.com/image/850/1000/xif0q/mobile/1/x/3/-original-imah8pdnxdwzazyy.jpeg?q=20&crop=false",
                            LongDescription = "The Samsung Galaxy S25 Ultra offers a 6.9-inch Dynamic AMOLED 2X display, Snapdragon 8 Elite processor, and a 200MP quad-camera system. The 5000mAh battery supports 45W fast charging for all-day use.",
                            Name = "Samsung Galaxy S25 Ultra",
                            OrderStage = "",
                            Price = 129999.0,
                            PublishDate = new DateOnly(2025, 4, 16),
                            Rating = 5,
                            ShortDescription = "A flagship phone with a powerful camera and AI capabilities.",
                            Stock = 10
                        },
                        new
                        {
                            Id = 102,
                            Brand = "Apple",
                            Category = "Smartphones",
                            ImageURL = "https://www.imagineonline.store/cdn/shop/files/iPhone_15_Pro_Max_Blue_Titanium_PDP_Image_Position-1__en-IN.jpg?v=1694758834",
                            LongDescription = "The iPhone 15 Pro Max features a titanium frame, A17 Pro chip, and a 48MP primary camera with enhanced low-light performance. A 6.7-inch Super Retina XDR display ensures stunning visuals.",
                            Name = "Apple iPhone 15 Pro Max",
                            OrderStage = "",
                            Price = 159999.0,
                            PublishDate = new DateOnly(2025, 4, 17),
                            Rating = 3,
                            ShortDescription = "Apple's premium iPhone with an advanced camera system.",
                            Stock = 8
                        },
                        new
                        {
                            Id = 103,
                            Brand = "OnePlus",
                            Category = "Smartphones",
                            ImageURL = "https://images.jdmagicbox.com/quickquotes/images_main/12-ram-16-gb-512-gb-flowy-emerald-272751531-d2abqe4q.png",
                            LongDescription = "The OnePlus 12 Pro is powered by the Snapdragon 8 Gen 3 processor, featuring a 6.8-inch 120Hz AMOLED display and a Hasselblad-tuned 64MP camera system. 100W fast charging ensures rapid power-up.",
                            Name = "OnePlus 12 Pro",
                            OrderStage = "",
                            Price = 74999.0,
                            PublishDate = new DateOnly(1, 1, 1),
                            Rating = 4,
                            ShortDescription = "A flagship killer with blazing-fast performance and premium design.",
                            Stock = 15
                        },
                        new
                        {
                            Id = 104,
                            Brand = "Google",
                            Category = "Smartphones",
                            ImageURL = "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/Pixel_8_Pro_in_Porcelain.max-936x936.format-webp.webp",
                            LongDescription = "The Google Pixel 8 Pro boasts an AI-powered Tensor G3 chip, a 50MP main camera, and exclusive Pixel software features. The 6.7-inch LTPO OLED display delivers stunning clarity.",
                            Name = "Google Pixel 8 Pro",
                            OrderStage = "",
                            Price = 106999.0,
                            PublishDate = new DateOnly(2025, 4, 19),
                            Rating = 1,
                            ShortDescription = "The best of Google’s AI-powered smartphone experience.",
                            Stock = 12
                        },
                        new
                        {
                            Id = 201,
                            Brand = "NVIDIA",
                            Category = "Graphic card",
                            ImageURL = "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/rtx-4090/geforce-ada-4090-web-og-1200x630.jpg",
                            LongDescription = "The NVIDIA GeForce RTX 4090 is the most powerful gaming GPU, featuring 24GB GDDR6X memory, 16384 CUDA cores, and DLSS 3.0 for ultra-high performance in 4K gaming.",
                            Name = "NVIDIA GeForce RTX 4090",
                            OrderStage = "",
                            Price = 189999.0,
                            PublishDate = new DateOnly(2025, 4, 20),
                            Rating = 5,
                            ShortDescription = "A flagship GPU with cutting-edge ray tracing and AI features.",
                            Stock = 7
                        },
                        new
                        {
                            Id = 202,
                            Brand = "AMD",
                            Category = "Graphic card",
                            ImageURL = "https://preview.redd.it/those-with-7900-xtx-hows-your-overclock-tuning-looking-like-v0-wibuxo51cusc1.jpeg?auto=webp&s=c9e003483c59df704342d6b434445fdc278b72e0",
                            LongDescription = "The AMD Radeon RX 7900 XTX delivers top-tier gaming performance with 24GB GDDR6 memory, RDNA 3 architecture, and advanced ray tracing for smooth 4K and high-refresh gaming.",
                            Name = "AMD Radeon RX 7900 XTX",
                            OrderStage = "",
                            Price = 108999.0,
                            PublishDate = new DateOnly(2025, 4, 16),
                            Rating = 2,
                            ShortDescription = "AMD’s flagship gaming GPU with high performance.",
                            Stock = 9
                        },
                        new
                        {
                            Id = 203,
                            Brand = "NVIDIA",
                            Category = "Graphic card",
                            ImageURL = "https://m.media-amazon.com/images/I/71-djDvKjfL.jpg",
                            LongDescription = "The RTX 4070 Ti is a high-performance gaming GPU featuring 12GB GDDR6X memory, DLSS 3.0, and 7680 CUDA cores, delivering excellent 1440p and 4K gaming performance.",
                            Name = "NVIDIA GeForce RTX 4070 Ti",
                            OrderStage = "",
                            Price = 79999.0,
                            PublishDate = new DateOnly(2025, 4, 19),
                            Rating = 5,
                            ShortDescription = "A powerful mid-high range GPU for gamers and creators.",
                            Stock = 12
                        },
                        new
                        {
                            Id = 204,
                            Brand = "AMD",
                            Category = "Graphic card",
                            ImageURL = "https://m.media-amazon.com/images/I/71GKfo5qtaL._AC_UF1000,1000_QL80_.jpg",
                            LongDescription = "The RX 7800 XT is designed for high-quality 1440p gaming, featuring 16GB GDDR6 memory, RDNA 3 architecture, and AI-powered graphics enhancements.",
                            Name = "AMD Radeon RX 7800 XT",
                            OrderStage = "",
                            Price = 57999.0,
                            PublishDate = new DateOnly(2025, 4, 15),
                            Rating = 2,
                            ShortDescription = "A great choice for high-performance 1440p gaming.",
                            Stock = 14
                        },
                        new
                        {
                            Id = 301,
                            Brand = "Sony",
                            Category = "Console",
                            ImageURL = "https://m.media-amazon.com/images/I/51fRDc+9ajL.jpg",
                            LongDescription = "The PlayStation 5 features an ultra-high-speed SSD, ray tracing capabilities, and 4K gaming at up to 120Hz. With the powerful AMD Ryzen Zen 2 processor and RDNA 2 GPU, it delivers an immersive gaming experience.",
                            Name = "Sony PlayStation 5",
                            OrderStage = "",
                            Price = 55999.0,
                            PublishDate = new DateOnly(2025, 4, 17),
                            Rating = 4,
                            ShortDescription = "Sony's next-gen console with ultra-fast performance and 4K gaming.",
                            Stock = 15
                        },
                        new
                        {
                            Id = 302,
                            Brand = "Microsoft",
                            Category = "Console",
                            ImageURL = "https://assets.xboxservices.com/assets/18/30/1830806b-d41d-40ce-a846-792df7d14e1d.jpg?n=Xbox-Series-X_Sharing_200x200_02.jpg",
                            LongDescription = "The Xbox Series X is Microsoft’s most powerful console, featuring 12 teraflops of power, 1TB SSD storage, and support for 4K gaming at up to 120FPS, ensuring seamless and responsive gameplay.",
                            Name = "Microsoft Xbox Series X",
                            OrderStage = "",
                            Price = 52999.0,
                            PublishDate = new DateOnly(2025, 4, 20),
                            Rating = 4,
                            ShortDescription = "Microsoft's most powerful 4K gaming console.",
                            Stock = 10
                        },
                        new
                        {
                            Id = 303,
                            Brand = "Nintendo",
                            Category = "Console",
                            ImageURL = "https://m.media-amazon.com/images/I/61nqNujSF2L.jpg",
                            LongDescription = "The Nintendo Switch OLED features a 7-inch OLED screen for vibrant colors, enhanced audio, and a sturdy adjustable stand, providing an immersive gaming experience in handheld, tabletop, or docked mode.",
                            Name = "Nintendo Switch OLED",
                            OrderStage = "",
                            Price = 34999.0,
                            PublishDate = new DateOnly(2025, 4, 19),
                            Rating = 4,
                            ShortDescription = "Nintendo's hybrid console with an upgraded OLED display.",
                            Stock = 12
                        },
                        new
                        {
                            Id = 304,
                            Brand = "Sony",
                            Category = "Console",
                            ImageURL = "https://rukminim2.flixcart.com/image/850/1000/xif0q/gamingconsole/z/b/w/-original-imagtk7vfbzqbjg6.jpeg?q=90&crop=false",
                            LongDescription = "The PS5 Digital Edition offers the same powerful performance as the standard PS5 but without a disc drive, making it perfect for digital game libraries and cloud gaming enthusiasts.",
                            Name = "Sony PlayStation 5 Digital Edition",
                            OrderStage = "",
                            Price = 45999.0,
                            PublishDate = new DateOnly(2025, 4, 17),
                            Rating = 1,
                            ShortDescription = "A digital-only version of the PlayStation 5.",
                            Stock = 8
                        },
                        new
                        {
                            Id = 305,
                            Brand = "Microsoft",
                            Category = "Console",
                            ImageURL = "https://www.designinfo.in/wp-content/uploads/2023/01/xbox-series-s-3-game-combo-2-485x485-optimized.jpg",
                            LongDescription = "The Xbox Series S is a compact and affordable next-gen console that delivers smooth 1440p gaming at up to 120FPS, powered by an advanced SSD for ultra-fast load times.",
                            Name = "Microsoft Xbox Series S",
                            OrderStage = "",
                            Price = 34999.0,
                            PublishDate = new DateOnly(2025, 4, 16),
                            Rating = 1,
                            ShortDescription = "A budget-friendly next-gen Xbox console with fast performance.",
                            Stock = 14
                        },
                        new
                        {
                            Id = 401,
                            Brand = "Apple",
                            Category = "Smart watch",
                            ImageURL = "https://www.apple.com/newsroom/images/2023/09/apple-introduces-the-advanced-new-apple-watch-series-9/article/Apple-Watch-S9-hero-230912_Full-Bleed-Image.jpg.large.jpg",
                            LongDescription = "The Apple Watch Series 9 features a brighter Always-On Retina display, a powerful S9 chip, and advanced health tracking, including ECG and blood oxygen monitoring. Seamlessly integrates with iOS devices.",
                            Name = "Apple Watch Series 9",
                            OrderStage = "",
                            Price = 41999.0,
                            PublishDate = new DateOnly(2025, 4, 16),
                            Rating = 3,
                            ShortDescription = "Apple’s latest smartwatch with advanced health and fitness tracking.",
                            Stock = 18
                        },
                        new
                        {
                            Id = 402,
                            Brand = "Samsung",
                            Category = "Smart watch",
                            ImageURL = "https://image-us.samsung.com/us/watches/galaxy-watch6-classic/images/galaxy-watch6-classic-kv-pc.jpg",
                            LongDescription = "The Galaxy Watch 6 Classic boasts a rotating bezel, Super AMOLED display, and powerful Exynos W930 processor. It offers advanced sleep tracking, body composition analysis, and seamless connectivity with Galaxy devices.",
                            Name = "Samsung Galaxy Watch 6 Classic",
                            OrderStage = "",
                            Price = 39999.0,
                            PublishDate = new DateOnly(2025, 4, 15),
                            Rating = 3,
                            ShortDescription = "A premium smartwatch with a classic design and advanced health features.",
                            Stock = 14
                        },
                        new
                        {
                            Id = 403,
                            Brand = "Garmin",
                            Category = "Smart watch",
                            ImageURL = "https://os-wordpress-media.s3.ap-south-1.amazonaws.com/blog/wp-content/uploads/2022/01/18235651/Garmin-Fenix-7-Cover.jpg",
                            LongDescription = "The Garmin Fenix 7 is a rugged smartwatch designed for adventurers, featuring GPS navigation, solar charging, heart rate monitoring, and multiple sports tracking modes for outdoor enthusiasts.",
                            Name = "Garmin Fenix 7",
                            OrderStage = "",
                            Price = 69999.0,
                            PublishDate = new DateOnly(2025, 4, 21),
                            Rating = 2,
                            ShortDescription = "A durable GPS smartwatch for extreme outdoor adventures.",
                            Stock = 7
                        },
                        new
                        {
                            Id = 404,
                            Brand = "Fitbit",
                            Category = "Smart watch",
                            ImageURL = "https://imageio.forbes.com/specials-images/imageserve/630c7317962396f5657ec5a1/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
                            LongDescription = "The Fitbit Sense 2 is a health-focused smartwatch with an ECG app, stress management tools, and an improved sensor suite for sleep tracking, making it an excellent choice for wellness enthusiasts.",
                            Name = "Fitbit Sense 2",
                            OrderStage = "",
                            Price = 25999.0,
                            PublishDate = new DateOnly(2025, 4, 18),
                            Rating = 2,
                            ShortDescription = "A health-centric smartwatch with stress and heart monitoring.",
                            Stock = 20
                        },
                        new
                        {
                            Id = 405,
                            Brand = "Amazfit",
                            Category = "Smart watch",
                            ImageURL = "https://us.amazfit.com/cdn/shop/products/PP-_-1_600x600.png?v=1663834312",
                            LongDescription = "The Amazfit GTR 4 features a stunning AMOLED display, built-in GPS, and an advanced BioTracker sensor for heart rate and SpO2 monitoring. Offers up to 14 days of battery life on a single charge.",
                            Name = "Amazfit GTR 4",
                            OrderStage = "",
                            Price = 16999.0,
                            PublishDate = new DateOnly(2025, 4, 16),
                            Rating = 5,
                            ShortDescription = "A stylish and long-lasting smartwatch with fitness tracking.",
                            Stock = 25
                        },
                        new
                        {
                            Id = 501,
                            Brand = "Alienware",
                            Category = "Pre build",
                            ImageURL = "https://os-wordpress-media.s3.ap-south-1.amazonaws.com/blog/wp-content/uploads/2022/09/29112344/Dell-Alienware-Aurora-R15.jpg",
                            LongDescription = "The Alienware Aurora R15 is a high-performance gaming desktop powered by the Intel Core i9-13900KF processor and NVIDIA GeForce RTX 4090. It features advanced cooling, customizable RGB lighting, and premium build quality.",
                            Name = "Alienware Aurora R15",
                            OrderStage = "",
                            Price = 389999.0,
                            PublishDate = new DateOnly(2025, 4, 19),
                            Rating = 5,
                            ShortDescription = "A powerful gaming PC with top-tier specs and premium cooling.",
                            Stock = 5
                        },
                        new
                        {
                            Id = 502,
                            Brand = "Asus",
                            Category = "Pre build",
                            ImageURL = "https://m.media-amazon.com/images/I/71WChkpECLL.jpg",
                            LongDescription = "The Asus ROG Strix G16 gaming PC comes with an Intel Core i7-13700KF processor, NVIDIA RTX 4070 Ti GPU, 32GB DDR5 RAM, and a 1TB NVMe SSD. Perfect for high-FPS gaming and content creation.",
                            Name = "Asus ROG Strix G16",
                            OrderStage = "",
                            Price = 229999.0,
                            PublishDate = new DateOnly(2025, 4, 21),
                            Rating = 4,
                            ShortDescription = "A high-performance gaming PC with an RTX 4070 Ti and powerful cooling.",
                            Stock = 8
                        },
                        new
                        {
                            Id = 503,
                            Brand = "HP",
                            Category = "Pre build",
                            ImageURL = "https://kaas.hpcloud.hp.com/PROD/v2/renderbinary/7573403/5038347/con-win-dt-p-omen-45l-gt22-1015nl-product-specifications/articuno-desktop",
                            LongDescription = "The HP Omen 45L gaming desktop features an AMD Ryzen 9 7900X, NVIDIA RTX 4080, 32GB DDR5 RAM, and a unique Cryo Chamber cooling system for extreme performance and efficiency.",
                            Name = "HP Omen 45L",
                            OrderStage = "",
                            Price = 269999.0,
                            PublishDate = new DateOnly(2025, 4, 18),
                            Rating = 5,
                            ShortDescription = "A premium gaming PC with advanced cooling and powerful hardware.",
                            Stock = 6
                        },
                        new
                        {
                            Id = 504,
                            Brand = "MSI",
                            Category = "Pre build",
                            ImageURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMAbfTV4NnUxIDwvzYDthWyZ78yTVZ8uASjw&s",
                            LongDescription = "The MSI Infinite RS 14th gaming PC packs an Intel Core i9-14900KF, NVIDIA RTX 4090, 64GB DDR5 RAM, and a 2TB NVMe SSD, offering ultimate gaming performance and seamless multitasking.",
                            Name = "MSI Infinite RS 14th",
                            OrderStage = "",
                            Price = 399999.0,
                            PublishDate = new DateOnly(2025, 4, 19),
                            Rating = 2,
                            ShortDescription = "A beastly gaming PC with the latest Intel and NVIDIA technology.",
                            Stock = 4
                        },
                        new
                        {
                            Id = 505,
                            Brand = "CyberPowerPC",
                            Category = "Pre build",
                            ImageURL = "https://m.media-amazon.com/images/I/71itNiAeHEL.jpg",
                            LongDescription = "CyberPowerPC Gamer Supreme is an affordable yet powerful gaming PC with an AMD Ryzen 7 7700X, RTX 4060 Ti, 16GB DDR5 RAM, and a 1TB SSD, offering smooth gaming performance for all modern titles.",
                            Name = "CyberPowerPC Gamer Supreme",
                            OrderStage = "",
                            Price = 149999.0,
                            PublishDate = new DateOnly(2025, 4, 19),
                            Rating = 3,
                            ShortDescription = "A budget-friendly gaming PC with excellent performance.",
                            Stock = 12
                        });
                });

            modelBuilder.Entity("eStore.Domain.Entity.TargetAudience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Product_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Product_Id");

                    b.ToTable("TargetAudiences");
                });

            modelBuilder.Entity("eStore.Domain.Entity.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eStore.Domain.Entity.Batch", b =>
                {
                    b.HasOne("eStore.Domain.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eStore.Domain.Entity.Order", b =>
                {
                    b.HasOne("eStore.Domain.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eStore.Domain.Entity.TargetAudience", b =>
                {
                    b.HasOne("eStore.Domain.Entity.Product", "Product")
                        .WithMany("TargetAudienceList")
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eStore.Domain.Entity.Product", b =>
                {
                    b.Navigation("TargetAudienceList");
                });
#pragma warning restore 612, 618
        }
    }
}
